services:
  - type: web
    name: tanzeel-video-downloader
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
